version: '3.7'
services:

  # Environment
  bank-db:
    image: postgres
    hostname: bank-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  java_app:
    build: .
    ports:
      - "8087:8087"
  prometheus:
    image: prom/prometheus:v2.32.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:8.3.3
    ports:
      - "3000:3000"